name: Contracts CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install asdf
        uses: asdf-vm/actions/setup@v2

      - name: Install plugins
        run: |
          asdf plugin add scarb
          asdf install scarb 2.11.3
          asdf global scarb 2.11.3

          asdf plugin add starknet-foundry
          asdf install starknet-foundry  0.44.0
          asdf global starknet-foundry  0.44.0

      - name: Build contracts
        run: |
          scarb build

      - name: Run tests
        run: |
          snforge test

      - name: Check formatting
        run: |
          scarb fmt --check